In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt

In [2]:
def selectkbest(indep_X,dep_Y,n):
        test = SelectKBest(score_func=chi2, k=n)
        fit1= test.fit(indep_X,dep_Y)
        # summarize scores       
        selectk_features = fit1.transform(indep_X)
        return selectk_features

In [3]:
def split_scalar(indep_X,dep_Y):
        X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
        sc = StandardScaler()
        X_train = sc.fit_transform(X_train)
        X_test = sc.transform(X_test)    
        return X_train, X_test, y_train, y_test

In [4]:
def r2_prediction(regressor,X_test,y_test):
     y_pred = regressor.predict(X_test)
     from sklearn.metrics import r2_score
     r2=r2_score(y_test,y_pred)
     return r2

In [5]:
def Linear(X_train,y_train,X_test):       
        # Fitting K-NN to the Training set
        from sklearn.linear_model import LinearRegression
        regressor = LinearRegression()
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2

In [6]:
def svm_linear(X_train,y_train,X_test):
                
        from sklearn.svm import SVR
        regressor = SVR(kernel = 'linear')
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2

In [7]:
    
def svm_NL(X_train,y_train,X_test):
                
        from sklearn.svm import SVR
        regressor = SVR(kernel = 'rbf')
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2

In [8]:
def Decision(X_train,y_train,X_test):
        
        # Fitting K-NN to the Training setC
        from sklearn.tree import DecisionTreeRegressor
        regressor = DecisionTreeRegressor(random_state = 0)
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2

In [9]:


def random(X_train,y_train,X_test):       
        # Fitting K-NN to the Training set
        from sklearn.ensemble import RandomForestRegressor
        regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2

In [10]:
def selectk_regression(acclin,accsvml,accsvmnl,accdes,accrf): 
    
    dataframe=pd.DataFrame(index=['ChiSquare'],columns=['Linear','SVMl','SVMnl','Decision','Random'
                                                                                     ])

    for number,idex in enumerate(dataframe.index):
        
        dataframe['Linear'][idex]=acclin[number]       
        dataframe['SVMl'][idex]=accsvml[number]
        dataframe['SVMnl'][idex]=accsvmnl[number]
        dataframe['Decision'][idex]=accdes[number]
        dataframe['Random'][idex]=accrf[number]
    return dataframe

In [11]:
dataset=pd.read_csv("Pre_melbourn.csv",index_col=None)

df2=dataset
df2.drop(['Suburb','Date','CouncilArea'],axis=1,inplace=True)
df2 = pd.get_dummies(df2, drop_first=True,dtype=int)

In [12]:
df2

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,YearBuilt,Propertycount,Type_t,Type_u,Regionname_Eastern Victoria,Regionname_Northern Metropolitan,Regionname_Northern Victoria,Regionname_South-Eastern Metropolitan,Regionname_Southern Metropolitan,Regionname_Western Metropolitan,Regionname_Western Victoria
0,2,1035000.0,2.5,3067,2.0,1.0,0,156.0,1900.0,4019,0,0,0,1,0,0,0,0,0
1,3,1465000.0,2.5,3067,3.0,2.0,0,134.0,1900.0,4019,0,0,0,1,0,0,0,0,0
2,4,1600000.0,2.5,3067,3.0,1.0,2,120.0,2014.0,4019,0,0,0,1,0,0,0,0,0
3,3,1876000.0,2.5,3067,4.0,2.0,0,245.0,1910.0,4019,0,0,0,1,0,0,0,0,0
4,2,1636000.0,2.5,3067,2.0,1.0,2,256.0,1890.0,4019,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8199,4,1245000.0,16.7,3150,4.0,2.0,2,652.0,1981.0,7392,0,0,0,0,0,1,0,0,0
8200,3,1031000.0,6.8,3016,3.0,2.0,2,333.0,1995.0,6380,0,0,0,0,0,0,0,1,0
8201,3,1170000.0,6.8,3016,3.0,2.0,4,436.0,1997.0,6380,0,0,0,0,0,0,0,1,0
8202,4,2500000.0,6.8,3016,4.0,1.0,5,866.0,1920.0,6380,0,0,0,0,0,0,0,1,0
8203,4,1285000.0,6.3,3013,4.0,1.0,1,362.0,1920.0,6543,0,0,0,0,0,0,0,1,0

In [13]:
df2.shape

(8204, 19)

In [14]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8204 entries, 0 to 8203
Data columns (total 19 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Rooms                                  8204 non-null   int64
 1   Price                                  8204 non-null   float64
 2   Distance                               8204 non-null   float64
 3   Postcode                               8204 non-null   int64
 4   Bedroom2                               8204 non-null   float64
 5   Bathroom                               8204 non-null   float64
 6   Car                                    8204 non-null   int64
 7   Landsize                               8204 non-null   float64
 8   YearBuilt                              8204 non-null   float64
 9   Propertycount                          8204 non-null   int64
 10  Type_t                                 8204 non-null   int32
 11  Type_u                                 8204 non-null   int32
 12  Regionname_Eastern Victoria            8204 non-null   int32
 13  Regionname_Northern Metropolitan       8204 non-null   int32
 14  Regionname_Northern Victoria           8204 non-null   int32
 15  Regionname_South-Eastern Metropolitan  8204 non-null   int32
 16  Regionname_Southern Metropolitan       8204 non-null   int32
 17  Regionname_Western Metropolitan        8204 non-null   int32
 18  Regionname_Western Victoria            8204 non-null   int32
dtypes: float64(6), int32(9), int64(4)
memory usage: 929.5 KB

In [15]:
indep_X=df2.drop(['Price'],axis=1)
dep_Y=df2['Price']

In [16]:

kbest=selectkbest(indep_X,dep_Y,5)      

acclin=[]
accsvml=[]
accsvmnl=[]
accdes=[]
accrf=[]

In [ ]:
X_train, X_test, y_train, y_test=split_scalar(kbest,dep_Y)  
for i in kbest:   
    r2_lin=Linear(X_train,y_train,X_test)
    acclin.append(r2_lin)
    
    r2_sl=svm_linear(X_train,y_train,X_test)    
    accsvml.append(r2_sl)
    
    r2_NL=svm_NL(X_train,y_train,X_test)
    accsvmnl.append(r2_NL)
    
    r2_d=Decision(X_train,y_train,X_test)
    accdes.append(r2_d)
    
    r2_r=random(X_train,y_train,X_test)
    accrf.append(r2_r)

In [ ]:
result=selectk_regression(acclin,accsvml,accsvmnl,accdes,accrf)

In [ ]:
result