In [35]:
import pandas as pd
import numpy as np
#import warnings
import warnings
warnings.filterwarnings('ignore')

In [2]:
dataset=pd.read_csv("Ai_companies.csv")

In [3]:
dataset

,Company Name,Description,Headquarters,Founded,Annual Revenue,Glassdoor Score
0,Alibaba Cloud,Best for Big Data Analytics,"Hangzhou, China",2009,$479.5 million,3.7/5
1,DataRobot,Best for Automated Machine Learning,"Boston, Massachusetts",2012,$338.2 million,3.7/5
2,Google,Best for AI Development,"Mountain View, California",1998,$305.6 billion,4.4/5
3,Hugging Face,Best for Deploying AI Models in the Cloud,"Brooklyn, New York",2016,$40 million,4.3/5
4,H2O.ai,Best for Time Series Forecasting,"Mountain View, California",2011,$69.2 million,3.1/5
...,...,...,...,...,...,...
95,Nuro,Best for Driverless Operation,"Mountain View, California",2016,$438.8 million,3.8/5
96,Pony.ai,Best for Robotruck Development,"Fremont, California",2016,$100 million,3.4/5
97,Tesla,Best for Electric Vehicles,"Austin, Texas",2003,$96.77 billion,3.6/5
98,Waymo,Best for Experience and Testing,"Mountain View, California",2016,$1.4 billion,3.7/5
99,Zoox,Best for Robotaxi Services,"Foster City, California",2014,$897.1 million,3.9/5

In [4]:
dataset.isnull().sum()

Company Name       0
Description        0
Headquarters       0
Founded            0
Annual Revenue     0
Glassdoor Score    2
dtype: int64

In [5]:
dataset.shape

(100, 6)

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Company Name     100 non-null    object
 1   Description      100 non-null    object
 2   Headquarters     100 non-null    object
 3   Founded          100 non-null    int64
 4   Annual Revenue   100 non-null    object
 5   Glassdoor Score  98 non-null     object
dtypes: int64(1), object(5)
memory usage: 4.8+ KB

In [7]:
dataset.fillna('NA',inplace=True)

In [8]:
dataset['Glassdoor Score'].value_counts()

Glassdoor Score
3.7/5    16
3.8/5    12
4.3/5    10
3.9/5     9
4.4/5     7
5-Apr     6
3.6/5     5
4.1/5     5
3.1/5     5
3.4/5     4
4.7/5     4
3.5/5     3
3.2/5     3
NA        2
4.8/5     2
4.2/5     2
4.9/5     1
4.5/5     1
4.6/5     1
3.3/5     1
2.9/5     1
Name: count, dtype: int64

In [9]:

# Convert column to string and remove unwanted characters
dataset['Glassdoor Score'] = dataset['Glassdoor Score'].astype(str).str.replace('/', '', regex=True)

# Convert column to numeric, setting errors='coerce' to handle non-numeric values
dataset['Glassdoor Score'] = pd.to_numeric(dataset['Glassdoor Score'], errors='coerce')

# Fill missing values with column mean
dataset['Glassdoor Score'].fillna(dataset['Glassdoor Score'].mean(), inplace=True)

C:\Users\Karpagavalli\AppData\Local\Temp\ipykernel_38436\3976090153.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Glassdoor Score'].fillna(dataset['Glassdoor Score'].mean(), inplace=True)

In [10]:
dataset.isnull().sum()

Company Name       0
Description        0
Headquarters       0
Founded            0
Annual Revenue     0
Glassdoor Score    0
dtype: int64

In [11]:
dataset['Glassdoor Score'].value_counts()

Glassdoor Score
3.750000    16
3.850000    12
4.350000    10
3.950000     9
3.945652     8
4.450000     7
3.150000     5
4.150000     5
3.650000     5
3.450000     4
4.750000     4
3.550000     3
3.250000     3
4.850000     2
4.250000     2
4.950000     1
4.550000     1
4.650000     1
3.350000     1
2.950000     1
Name: count, dtype: int64

In [12]:
# Sample dataset with mixed revenue formats
#dataset['Annual Revenue'] = dataset['Annual Revenue'].str.replace('$', '', regex=False)

In [13]:
# Function to convert revenue to millions
def convert_to_million(value):
    if isinstance(value, str):  # Ensure value is a string
        value = value.replace('$', '').strip().lower()  # Remove '$' and convert to lowercase
        
        if 'b' in value or 'billion' in value:  # Handle billions
            return float(value.replace('billion', '').replace('b', '').strip()) * 1000
        elif 'm' in value or 'million' in value:  # Handle millions
            return float(value.replace('million', '').replace('m', '').strip())
    
    return None  # Return None for unexpected values

# Apply conversion function
dataset['Annual Revenue'] = dataset['Annual Revenue'].apply(convert_to_million)

In [14]:
pd.set_option('display.max_rows',None)
dataset['Annual Revenue'].value_counts()

Annual Revenue
18.80        2
25.00        2
5.00         2
479.50       1
87.70        1
514.00       1
90.00        1
6.00         1
945.20       1
35.50        1
85000.00     1
38.00        1
2000.00      1
83650.00     1
7.40         1
9.20         1
68000.00     1
96.60        1
22.40        1
75.00        1
1950.00      1
13.40        1
55.60        1
250.00       1
15.70        1
88.80        1
36.00        1
34.00        1
1400.00      1
96770.00     1
100.00       1
438.80       1
342.00       1
2.50         1
196.20       1
1560.00      1
36.20        1
27.60        1
231.00       1
14.70        1
500.00       1
7.00         1
2.70         1
18.00        1
176.00       1
230.00       1
77.70        1
1550.00      1
267.00       1
2600.00      1
338.20       1
31400.00     1
21.40        1
663.90       1
1130.00      1
62.50        1
544.30       1
120.00       1
125.90       1
48.50        1
1000.00      1
189.00       1
61900.00     1
730.00       1
2170.00      1
596.40       1
158.70       1
195.00       1
1.20         1
69.20        1
40.00        1
305600.00    1
121.80       1
612.70       1
1830.00      1
34.90        1
2066.00      1
900.00       1
4485.00      1
1500.00      1
574790.00    1
5.70         1
496.26       1
211000.00    1
237.00       1
3.10         1
140.00       1
12.30        1
3000.00      1
33540.00     1
525.10       1
49954.00     1
1570.00      1
37.70        1
210.00       1
4208.00      1
897.10       1
Name: count, dtype: int64

In [15]:
temp_df=dataset['Headquarters'].str.split(",",n=1,expand=True)
temp_df

                  0                                    1
0          Hangzhou                                China
1            Boston                        Massachusetts
2     Mountain View                           California
3          Brooklyn                             New York
4     Mountain View                           California
5     San Francisco                           California
6     San Francisco                           California
7           Chicago                             Illinois
8         San Diego                           California
9           Chennai                                India
10        Cambridge                        Massachusetts
11         Tel-Aviv                               Israel
12         New York                        United States
13    San Francisco                           California
14          Chennai                                India
15     Redwood City                           California
16       El Segundo                           California
17           Boston                        Massachusetts
18        Cambridge                       United Kingdom
19         New York                             New York
20        Sunnyvale                           California
21    Mountain View                           California
22           London                       United Kingdom
23         San Jose                           California
24           Armonk                             New York
25  King of Prussia                         Pennsylvania
26         New York                             New York
27    San Francisco                           California
28        Sunnyvale                           California
29          Toronto                               Canada
30     Redwood City                           California
31           Austin                                Texas
32       Burlington                        Massachusetts
33         Walldorf                              Germany
34             Cary                       North Carolina
35        Manhattan                             New York
36           Boston                        Massachusetts
37          Chicago                             Illinois
38    American Fork                                 Utah
39          Redmond                           Washington
40           Tysons                             Virginia
41    San Francisco                           California
42          Seattle      Washington; Arlington, Virginia
43    San Francisco                           California
44         Waterloo                               Canada
45        Palo Alto                           California
46          Bozeman                              Montana
47        San Diego                           California
48         New York                             New York
49         New York                             New York
50     Redwood City                           California
51         Bellevue                           Washington
52    San Francisco                           California
53           London                       United Kingdom
54          Ventura                           California
55           KrakÃ³w   Poland and New York City, New York
56       Pittsburgh                         Pennsylvania
57           London                       United Kingdom
58             Pune                                India
59     Redwood City                           California
60        Cambridge                         Massachusets
61           Munich                              Germany
62       Somerville                        Massachusetts
63          Toronto                               Canada
64       Menlo Park                           California
65    San Francisco                           California
66      Santa Clara                           California
67         Shenzhen                                China
68         New York                             New York
69          Houston                                Texas
70    San Francisco                           California
71         San Jose                           California
72        San Mateo                           California
73    San Francisco                           California
74     Fort Collins                             Colorado
75           Boston                        Massachusetts
76     Redwood City                           California
77          Chicago                             Illinois
78        Cambridge                       United Kingdom
79    San Francisco                           California
80         New York                             New York
81           Boston                        Massachusetts
82           London                       United Kingdom
83           London                                   UK
84          Bristol                       United Kingdom
85        Rockville                             Maryland
86        Hong Kong                                 None
87          Tangent                               Oregon
88          Waltham                        Massachusetts
89           Austin                                Texas
90         Longmont                             Colorado
91          Bedford                        Massachusetts
92        San Mateo                           California
93           Dublin                           California
94       Costa Mesa                           California
95    Mountain View                           California
96          Fremont                           California
97           Austin                                Texas
98    Mountain View                           California
99      Foster City                           California

In [16]:
dataset['Places']=temp_df[0]
dataset['Headquarters']=temp_df[1]
dataset

,Company Name,Description,Headquarters,Founded,Annual Revenue,Glassdoor Score,Places
0,Alibaba Cloud,Best for Big Data Analytics,China,2009,479.50,3.750000,Hangzhou
1,DataRobot,Best for Automated Machine Learning,Massachusetts,2012,338.20,3.750000,Boston
2,Google,Best for AI Development,California,1998,305600.00,4.450000,Mountain View
3,Hugging Face,Best for Deploying AI Models in the Cloud,New York,2016,40.00,4.350000,Brooklyn
4,H2O.ai,Best for Time Series Forecasting,California,2011,69.20,3.150000,Mountain View
5,Rasa,Best for Managing Conversational AI Applications,California,2016,18.80,3.950000,San Francisco
6,Replicate,Best for Scalability and Cost-Effectiveness,California,2019,1.20,3.945652,San Francisco
7,ActiveCampaign,Best for Email and Marketing Automation,Illinois,2003,195.00,3.750000,Chicago
8,ClickUp,Best for Project Management,California,2017,158.70,3.450000,San Diego
9,Freshworks,Best for Intelligent Customer Engagement,India,2010,596.40,3.850000,Chennai
10,HubSpot,Best for Scaling Businesses,Massachusetts,2006,2170.00,4.150000,Cambridge
11,monday.com,Best for Collaborative Work Management,Israel,2012,730.00,4.450000,Tel-Aviv
12,Pipedrive,Best for Growing Small Businesses,United States,2010,189.00,3.650000,New York
13,"Salesforce, Inc.",Best for Predictive Analytics,California,1999,31400.00,4.150000,San Francisco
14,Zoho Corporation,Best for Smart Business Tools,India,1996,1000.00,4.550000,Chennai
15,Anomali,Best for Threat Intelligence Aggregation,California,2013,48.50,3.450000,Redwood City
16,CUJO AI,Best for Advanced Network Security,California,2015,125.90,4.350000,El Segundo
17,Cybereason,Best for AI-Powered Endpoint Protection,Massachusetts,2012,120.00,3.150000,Boston
18,Darktrace,Best for AI-Driven Cybersecurity,United Kingdom,2013,544.30,3.350000,Cambridge
19,Deep Instinct,Best for Deep Learning-Based Threat Prevention...,New York,2015,62.50,3.850000,New York
20,Proofpoint,Best for Email Security and Compliance,California,2002,1130.00,3.850000,Sunnyvale
21,SentinelOne,Best for Autonomous Response to Cyberthreats,California,2013,663.90,4.850000,Mountain View
22,Tessian,Best for Preventing Human-Error Security Incid...,United Kingdom,2013,21.40,3.950000,London
23,Vectra AI,Best for Threat Detection and Response,California,2011,121.80,4.350000,San Jose
24,IBM (International Business Machines Corporation),Best for Data Preparation and Integration,New York,1911,61900.00,4.150000,Armonk
25,Qlik,Best for Self-Service Business Intelligence Tools,Pennsylvania,1993,612.70,3.750000,King of Prussia
26,Sisense,Best for Business Intelligence,New York,2004,140.00,3.250000,New York
27,Splunk,Best for Business and Web Analytics,California,2003,4208.00,3.950000,San Francisco
28,"ThoughtSpot, Inc",Best for Search-Driven Analytics,California,2012,210.00,3.950000,Sunnyvale
29,Ataccama,Best for Versatile Data Management,Canada,2007,37.70,4.450000,Toronto
30,Informatica,Best for Multi-Hybrid Workload Management,California,1993,1570.00,3.950000,Redwood City
31,Oracle,Best for Large-Scale AI Model Training,Texas,1977,49954.00,3.850000,Austin
32,Precisely,Best for Customized Data Solutions,Massachusetts,1968,525.10,4.150000,Burlington
33,SAP,Best for Data-Driven Decision-Making,Germany,1972,33540.00,4.350000,Walldorf
34,SAS,Best for Comprehensive Analytics and Data Mana...,North Carolina,1976,3000.00,3.945652,Cary
35,AIMLEAP Outsource BigData,Best for Expert Data Management Services,New York,2012,12.30,4.650000,Manhattan
36,Akkio,Best for Data Cleaning and Transformation,Massachusetts,2019,3.10,3.945652,Boston
37,Analytics8,Best for Accelerating the Development of Data ...,Illinois,2002,34.90,4.750000,Chicago
38,Domo,Best for Real-Time Enterprise Data Access,Utah,2010,237.00,4.350000,American Fork
39,Microsoft,Best for Advanced Data Analysis and Predictive...,Washington,1975,211000.00,4.350000,Redmond
40,MicroStrategy,Best for Enterprise Analytics,Virginia,1989,496.26,3.750000,Tysons
41,MonkeyLearn,Best for Extracting Insights from Unstructured...,California,2014,5.70,4.350000,San Francisco
42,Amazon,Best for Managing and Analyzing Large Datasets,"Washington; Arlington, Virginia",1994,574790.00,3.750000,Seattle
43,Databricks,Best for Large-Scale Data Engineering,California,2013,1500.00,4.450000,San Francisco
44,OpenText,Best for Advanced Data Management,Canada,1991,4485.00,3.550000,Waterloo
45,Rubrik,Best for Proactive Threat Protection in VMware...,California,2014,900.00,3.850000,Palo Alto
46,Snowflake,Best for Cloud-Based Data Warehousing,Montana,2012,2066.00,3.945652,Bozeman
47,Teradata,Best for Integrating Diverse Data Sources,California,1979,1830.00,3.850000,San Diego
48,AlphaSense,Best for Intelligent Search Engine,New York,2011,2600.00,3.950000,New York
49,Bizzabo,Best for Hybrid Event Management,New York,2011,36.00,3.750000,New York
50,C3 AI,Best for Rapid AI Application Development,California,2009,267.00,3.550000,Redwood City
51,Icertis,Best for End-to-End Contract Management,Washington,2009,250.00,3.550000,Bellevue
52,People.ai,Best for Sales Coaching,California,2016,55.60,4.450000,San Francisco
53,Phrasee,Best for High-Performing Marketing Language,United Kingdom,2015,13.40,3.945652,London
54,The Trade Desk,Best for Data-Driven Audience Targeting,California,2009,1950.00,3.850000,Ventura
55,Brainly,Best for Personalized Learning Experiences,"Poland and New York City, New York",2009,75.00,3.150000,KrakÃ³w
56,Carnegie Learning,Best for Data-Driven Decision-Making for Educa...,Pennsylvania,1998,22.40,3.750000,Pittsburgh
57,CENTURY Tech,Best for Increasing Student Engagement,United Kingdom,2013,18.80,3.945652,London
58,Harbinger Group,Best for Educational Content Creation,India,1990,96.60,4.350000,Pune
59,AutoGrid,Best for Distributed Energy Optimization,California,2011,25.00,4.350000,Redwood City
60,GE Vernova,Best for Wind Turbine Model,Massachusets,2022,68000.00,3.850000,Cambridge
61,Siemens,Best for Industrial Automation and Digitalization,Germany,1847,83650.00,4.250000,Munich
62,Via Science,Best for Web3-Native Security and Privacy,Massachusetts,2016,7.40,4.950000,Somerville
63,Xanadu,Best for Quantum Computing,Canada,2016,87.70,4.450000,Toronto
64,AIBrain,Best for Conversational AI,California,2012,5.00,2.950000,Menlo Park
65,OpenAI,Best for Natural Language Processing (NLP) Res...,California,2015,2000.00,4.250000,San Francisco
66,SoundHound,Best for Music Recognition,California,2005,38.00,3.250000,Santa Clara
67,Tencent,Best for Social Media and Communication,China,1998,85000.00,3.945652,Shenzhen
68,Cleo,Best for Building Credit,New York,2016,35.50,3.850000,New York
69,HighRadius,Best for Automating Accounts Receivable (AR) P...,Texas,2006,945.20,3.650000,Houston
70,Numerai,Best for Crowdsourcing AI Predictions,California,2015,6.00,3.450000,San Francisco
71,Signifyd,Best for Chargeback Guarantee,California,2011,90.00,4.750000,San Jose
72,Upstart,Best for Risk Assessment for Lenders,California,2012,514.00,3.850000,San Mateo
73,Atomwise,Best for Drug Discovery,California,2012,15.70,3.750000,San Francisco
74,Enlitic,Best for AI-Driven Medical Imaging Analysis So...,Colorado,2014,9.20,3.850000,Fort Collins
75,PathAI,Best for Comprehensive Precision Pathology Sol...,Massachusetts,2016,88.80,3.150000,Boston
76,Suki AI,Best for Clinical Documentation,California,2017,25.00,4.450000,Redwood City
77,Tempus Labs,Best for Precision Medicine,Illinois,2015,231.00,3.250000,Chicago
78,AVEVA,Best for Asset Performance,United Kingdom,1967,1550.00,3.950000,Cambridge
79,Bright Machines,Best for Software-Defined Manufacturing,California,2018,77.70,3.650000,San Francisco
80,Dataiku,Best for Democratizing AI,New York,2013,230.00,3.750000,New York
81,DataRobot,Best for Automated Machine Learning (AutoML),Massachusetts,2012,176.00,3.750000,Boston
82,DataToBiz,Best for Data-Driven Decision-Making,United Kingdom,2018,5.00,4.850000,London
83,Domino Data Lab,Best for Predictive Maintenance,UK,2013,18.00,3.750000,London
84,Graphcore,Best for IPU Architecture,United Kingdom,2016,2.70,3.945652,Bristol
85,N5 Sensors,Best for Detecting Chemical Threats and Accidents,Maryland,2012,7.00,3.950000,Rockville
86,SenseTime,Best for Facial Recognition,None,2014,500.00,3.650000,Hong Kong
87,Agility Robotics,Best for Developing Agile and Mobile Robots,Oregon,2015,14.70,3.750000,Tangent
88,Boston Dynamics,Best for Research and Development,Massachusetts,1992,27.60,4.750000,Waltham
89,Diligent Robotics,Best for Healthcare Data Integration and Analysis,Texas,2017,34.00,3.150000,Austin
90,Honeybee Robotics,Best for Developing Robotic Systems for Challe...,Colorado,1983,36.20,3.750000,Longmont
91,iRobot,Best for Consumer and Military Robotic Solutions,Massachusetts,1990,1560.00,3.750000,Bedford
92,Skydio,Best for Autonomous Drone Solutions,California,2014,196.20,4.750000,San Mateo
93,"AEye, Inc.",Best for Adaptive Sensing,California,2013,2.50,4.150000,Dublin
94,Anduril Industries,Best for Advanced Defense Technology,California,2017,342.00,4.350000,Costa Mesa
95,Nuro,Best for Driverless Operation,California,2016,438.80,3.850000,Mountain View
96,Pony.ai,Best for Robotruck Development,California,2016,100.00,3.450000,Fremont
97,Tesla,Best for Electric Vehicles,Texas,2003,96770.00,3.650000,Austin
98,Waymo,Best for Experience and Testing,California,2016,1400.00,3.750000,Mountain View
99,Zoox,Best for Robotaxi Services,California,2014,897.10,3.950000,Foster City

In [17]:
dataset.drop(["Places"],axis=1,inplace=True)

In [18]:
dataset.fillna('NA',inplace=True)

In [19]:
dataset

,Company Name,Description,Headquarters,Founded,Annual Revenue,Glassdoor Score
0,Alibaba Cloud,Best for Big Data Analytics,China,2009,479.50,3.750000
1,DataRobot,Best for Automated Machine Learning,Massachusetts,2012,338.20,3.750000
2,Google,Best for AI Development,California,1998,305600.00,4.450000
3,Hugging Face,Best for Deploying AI Models in the Cloud,New York,2016,40.00,4.350000
4,H2O.ai,Best for Time Series Forecasting,California,2011,69.20,3.150000
5,Rasa,Best for Managing Conversational AI Applications,California,2016,18.80,3.950000
6,Replicate,Best for Scalability and Cost-Effectiveness,California,2019,1.20,3.945652
7,ActiveCampaign,Best for Email and Marketing Automation,Illinois,2003,195.00,3.750000
8,ClickUp,Best for Project Management,California,2017,158.70,3.450000
9,Freshworks,Best for Intelligent Customer Engagement,India,2010,596.40,3.850000
10,HubSpot,Best for Scaling Businesses,Massachusetts,2006,2170.00,4.150000
11,monday.com,Best for Collaborative Work Management,Israel,2012,730.00,4.450000
12,Pipedrive,Best for Growing Small Businesses,United States,2010,189.00,3.650000
13,"Salesforce, Inc.",Best for Predictive Analytics,California,1999,31400.00,4.150000
14,Zoho Corporation,Best for Smart Business Tools,India,1996,1000.00,4.550000
15,Anomali,Best for Threat Intelligence Aggregation,California,2013,48.50,3.450000
16,CUJO AI,Best for Advanced Network Security,California,2015,125.90,4.350000
17,Cybereason,Best for AI-Powered Endpoint Protection,Massachusetts,2012,120.00,3.150000
18,Darktrace,Best for AI-Driven Cybersecurity,United Kingdom,2013,544.30,3.350000
19,Deep Instinct,Best for Deep Learning-Based Threat Prevention...,New York,2015,62.50,3.850000
20,Proofpoint,Best for Email Security and Compliance,California,2002,1130.00,3.850000
21,SentinelOne,Best for Autonomous Response to Cyberthreats,California,2013,663.90,4.850000
22,Tessian,Best for Preventing Human-Error Security Incid...,United Kingdom,2013,21.40,3.950000
23,Vectra AI,Best for Threat Detection and Response,California,2011,121.80,4.350000
24,IBM (International Business Machines Corporation),Best for Data Preparation and Integration,New York,1911,61900.00,4.150000
25,Qlik,Best for Self-Service Business Intelligence Tools,Pennsylvania,1993,612.70,3.750000
26,Sisense,Best for Business Intelligence,New York,2004,140.00,3.250000
27,Splunk,Best for Business and Web Analytics,California,2003,4208.00,3.950000
28,"ThoughtSpot, Inc",Best for Search-Driven Analytics,California,2012,210.00,3.950000
29,Ataccama,Best for Versatile Data Management,Canada,2007,37.70,4.450000
30,Informatica,Best for Multi-Hybrid Workload Management,California,1993,1570.00,3.950000
31,Oracle,Best for Large-Scale AI Model Training,Texas,1977,49954.00,3.850000
32,Precisely,Best for Customized Data Solutions,Massachusetts,1968,525.10,4.150000
33,SAP,Best for Data-Driven Decision-Making,Germany,1972,33540.00,4.350000
34,SAS,Best for Comprehensive Analytics and Data Mana...,North Carolina,1976,3000.00,3.945652
35,AIMLEAP Outsource BigData,Best for Expert Data Management Services,New York,2012,12.30,4.650000
36,Akkio,Best for Data Cleaning and Transformation,Massachusetts,2019,3.10,3.945652
37,Analytics8,Best for Accelerating the Development of Data ...,Illinois,2002,34.90,4.750000
38,Domo,Best for Real-Time Enterprise Data Access,Utah,2010,237.00,4.350000
39,Microsoft,Best for Advanced Data Analysis and Predictive...,Washington,1975,211000.00,4.350000
40,MicroStrategy,Best for Enterprise Analytics,Virginia,1989,496.26,3.750000
41,MonkeyLearn,Best for Extracting Insights from Unstructured...,California,2014,5.70,4.350000
42,Amazon,Best for Managing and Analyzing Large Datasets,"Washington; Arlington, Virginia",1994,574790.00,3.750000
43,Databricks,Best for Large-Scale Data Engineering,California,2013,1500.00,4.450000
44,OpenText,Best for Advanced Data Management,Canada,1991,4485.00,3.550000
45,Rubrik,Best for Proactive Threat Protection in VMware...,California,2014,900.00,3.850000
46,Snowflake,Best for Cloud-Based Data Warehousing,Montana,2012,2066.00,3.945652
47,Teradata,Best for Integrating Diverse Data Sources,California,1979,1830.00,3.850000
48,AlphaSense,Best for Intelligent Search Engine,New York,2011,2600.00,3.950000
49,Bizzabo,Best for Hybrid Event Management,New York,2011,36.00,3.750000
50,C3 AI,Best for Rapid AI Application Development,California,2009,267.00,3.550000
51,Icertis,Best for End-to-End Contract Management,Washington,2009,250.00,3.550000
52,People.ai,Best for Sales Coaching,California,2016,55.60,4.450000
53,Phrasee,Best for High-Performing Marketing Language,United Kingdom,2015,13.40,3.945652
54,The Trade Desk,Best for Data-Driven Audience Targeting,California,2009,1950.00,3.850000
55,Brainly,Best for Personalized Learning Experiences,"Poland and New York City, New York",2009,75.00,3.150000
56,Carnegie Learning,Best for Data-Driven Decision-Making for Educa...,Pennsylvania,1998,22.40,3.750000
57,CENTURY Tech,Best for Increasing Student Engagement,United Kingdom,2013,18.80,3.945652
58,Harbinger Group,Best for Educational Content Creation,India,1990,96.60,4.350000
59,AutoGrid,Best for Distributed Energy Optimization,California,2011,25.00,4.350000
60,GE Vernova,Best for Wind Turbine Model,Massachusets,2022,68000.00,3.850000
61,Siemens,Best for Industrial Automation and Digitalization,Germany,1847,83650.00,4.250000
62,Via Science,Best for Web3-Native Security and Privacy,Massachusetts,2016,7.40,4.950000
63,Xanadu,Best for Quantum Computing,Canada,2016,87.70,4.450000
64,AIBrain,Best for Conversational AI,California,2012,5.00,2.950000
65,OpenAI,Best for Natural Language Processing (NLP) Res...,California,2015,2000.00,4.250000
66,SoundHound,Best for Music Recognition,California,2005,38.00,3.250000
67,Tencent,Best for Social Media and Communication,China,1998,85000.00,3.945652
68,Cleo,Best for Building Credit,New York,2016,35.50,3.850000
69,HighRadius,Best for Automating Accounts Receivable (AR) P...,Texas,2006,945.20,3.650000
70,Numerai,Best for Crowdsourcing AI Predictions,California,2015,6.00,3.450000
71,Signifyd,Best for Chargeback Guarantee,California,2011,90.00,4.750000
72,Upstart,Best for Risk Assessment for Lenders,California,2012,514.00,3.850000
73,Atomwise,Best for Drug Discovery,California,2012,15.70,3.750000
74,Enlitic,Best for AI-Driven Medical Imaging Analysis So...,Colorado,2014,9.20,3.850000
75,PathAI,Best for Comprehensive Precision Pathology Sol...,Massachusetts,2016,88.80,3.150000
76,Suki AI,Best for Clinical Documentation,California,2017,25.00,4.450000
77,Tempus Labs,Best for Precision Medicine,Illinois,2015,231.00,3.250000
78,AVEVA,Best for Asset Performance,United Kingdom,1967,1550.00,3.950000
79,Bright Machines,Best for Software-Defined Manufacturing,California,2018,77.70,3.650000
80,Dataiku,Best for Democratizing AI,New York,2013,230.00,3.750000
81,DataRobot,Best for Automated Machine Learning (AutoML),Massachusetts,2012,176.00,3.750000
82,DataToBiz,Best for Data-Driven Decision-Making,United Kingdom,2018,5.00,4.850000
83,Domino Data Lab,Best for Predictive Maintenance,UK,2013,18.00,3.750000
84,Graphcore,Best for IPU Architecture,United Kingdom,2016,2.70,3.945652
85,N5 Sensors,Best for Detecting Chemical Threats and Accidents,Maryland,2012,7.00,3.950000
86,SenseTime,Best for Facial Recognition,NA,2014,500.00,3.650000
87,Agility Robotics,Best for Developing Agile and Mobile Robots,Oregon,2015,14.70,3.750000
88,Boston Dynamics,Best for Research and Development,Massachusetts,1992,27.60,4.750000
89,Diligent Robotics,Best for Healthcare Data Integration and Analysis,Texas,2017,34.00,3.150000
90,Honeybee Robotics,Best for Developing Robotic Systems for Challe...,Colorado,1983,36.20,3.750000
91,iRobot,Best for Consumer and Military Robotic Solutions,Massachusetts,1990,1560.00,3.750000
92,Skydio,Best for Autonomous Drone Solutions,California,2014,196.20,4.750000
93,"AEye, Inc.",Best for Adaptive Sensing,California,2013,2.50,4.150000
94,Anduril Industries,Best for Advanced Defense Technology,California,2017,342.00,4.350000
95,Nuro,Best for Driverless Operation,California,2016,438.80,3.850000
96,Pony.ai,Best for Robotruck Development,California,2016,100.00,3.450000
97,Tesla,Best for Electric Vehicles,Texas,2003,96770.00,3.650000
98,Waymo,Best for Experience and Testing,California,2016,1400.00,3.750000
99,Zoox,Best for Robotaxi Services,California,2014,897.10,3.950000

In [21]:
dataset['Headquarters'].value_counts()

Headquarters
 California                            38
 Massachusetts                         10
 New York                               9
 United Kingdom                         7
 Texas                                  4
 Illinois                               3
 India                                  3
 Canada                                 3
 China                                  2
 Germany                                2
 Colorado                               2
 Washington                             2
 Pennsylvania                           2
 Poland and New York City, New York     1
 UK                                     1
 Maryland                               1
NA                                      1
 Massachusets                           1
 North Carolina                         1
 Montana                                1
 Washington; Arlington, Virginia        1
 Virginia                               1
 Utah                                   1
 United States                          1
 Israel                                 1
 Oregon                                 1
Name: count, dtype: int64

In [22]:
dataset['Headquarters'] = dataset['Headquarters'].str.replace('Massachusets','Massachusetts',regex=True)
dataset['Headquarters'] = dataset['Headquarters'].str.replace('UK','United Kingdom',regex=True)
dataset['Headquarters'] = dataset['Headquarters'].str.replace('Poland and New York City, New York','Poland',regex=True)
dataset['Headquarters'] = dataset['Headquarters'].str.replace('NA','Hong Kong',regex=True)

In [25]:
dataset['Headquarters'].value_counts()

Headquarters
 California                         38
 Massachusetts                      11
 New York                            9
 United Kingdom                      8
 Texas                               4
 Illinois                            3
 India                               3
 Canada                              3
 China                               2
 Colorado                            2
 Washington                          2
 Germany                             2
 Pennsylvania                        2
 North Carolina                      1
 Utah                                1
 United States                       1
 Virginia                            1
 Washington; Arlington, Virginia     1
 Montana                             1
 Poland                              1
 Israel                              1
 Maryland                            1
Hong Kong                            1
 Oregon                              1
Name: count, dtype: int64

In [26]:
dataset.isnull().sum()

Company Name       0
Description        0
Headquarters       0
Founded            0
Annual Revenue     0
Glassdoor Score    0
dtype: int64

In [27]:
dataset.describe()

           Founded  Annual Revenue  Glassdoor Score
count   100.000000      100.000000       100.000000
mean   2004.360000    16494.258600         3.945652
std      22.184953    69473.696996         0.432029
min    1847.000000        1.200000         2.950000
25%    2002.750000       35.350000         3.750000
50%    2012.000000      195.600000         3.897826
75%    2015.000000     1197.500000         4.350000
max    2022.000000   574790.000000         4.950000

In [30]:
def QuanQual(dataset):
    quan=[]
    qual=[]
    for ColumnName in dataset.columns:
        #print(ColumnName)
        if (dataset[ColumnName].dtypes=='O'):
            #print("qual")
            qual.append(ColumnName)
        else:
            #print("quan")
            quan.append(ColumnName)
    return quan,qual

In [31]:
quan,qual=QuanQual(dataset)

In [32]:
quan

['Founded', 'Annual Revenue', 'Glassdoor Score']

In [33]:
qual

['Company Name', 'Description', 'Headquarters']

In [40]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode",
                                "Q1:25%","Q2:50%","Q3:75%","Q4:99%","Q5:100%",
                                "IQR","1.5Rule","Lesser","Greater","Min","Max"],columns=quan)

for ColumnName in quan:
    
    descriptive[ColumnName]["Mean"]=dataset[ColumnName].mean()
    descriptive[ColumnName]["Mean"]=dataset[ColumnName].mean()
    descriptive[ColumnName]["Median"]=dataset[ColumnName].median()
    descriptive[ColumnName]["Mode"]=dataset[ColumnName].mode()[0]
    descriptive[ColumnName]["Q1:25%"]=dataset.describe()[ColumnName]["25%"] 
    descriptive[ColumnName]["Q2:50%"]=dataset.describe()[ColumnName]["50%"]
    descriptive[ColumnName]["Q3:75%"]=dataset.describe()[ColumnName]["75%"]
    descriptive[ColumnName]["Q4:99%"]=np.percentile(dataset[ColumnName],99)
    descriptive[ColumnName]["Q5:100%"]=dataset.describe()[ColumnName]["max"]
    descriptive[ColumnName]["IQR"]= descriptive[ColumnName]["Q3:75%"]-descriptive[ColumnName]["Q1:25%"]
    descriptive[ColumnName]["1.5Rule"]=1.5*descriptive[ColumnName]["IQR"]
    descriptive[ColumnName]["Lesser"]=descriptive[ColumnName]["Q1:25%"]-descriptive[ColumnName]["1.5Rule"]
    descriptive[ColumnName]["Greater"]=descriptive[ColumnName]["Q3:75%"]+descriptive[ColumnName]["1.5Rule"]
    descriptive[ColumnName]["Min"]=dataset[ColumnName].min()
    descriptive[ColumnName]["Max"]=dataset[ColumnName].max()

In [41]:
descriptive

          Founded Annual Revenue Glassdoor Score
Mean      2004.36     16494.2586        3.945652
Median     2012.0          195.6        3.897826
Mode         2012            5.0            3.75
Q1:25%    2002.75          35.35            3.75
Q2:50%     2012.0          195.6        3.897826
Q3:75%     2015.0         1197.5            4.35
Q4:99%    2019.03       308291.9           4.851
Q5:100%    2022.0       574790.0            4.95
IQR         12.25        1162.15             0.6
1.5Rule    18.375       1743.225             0.9
Lesser   1984.375      -1707.875            2.85
Greater  2033.375       2940.725            5.25
Min          1847            1.2            2.95
Max          2022       574790.0            4.95

In [42]:
lesser=[]
greater=[]
for columnName in quan:
    if(descriptive[columnName]["Min"]<descriptive[columnName]["Lesser"]):
        lesser.append(columnName)
        if(descriptive[columnName]["Max"]>descriptive[columnName]["Greater"]):
            greater.append(columnName)

In [43]:
lesser

['Founded']

In [44]:
greater

[]

In [45]:
for columnName in lesser:
    dataset[columnName][dataset[columnName] < descriptive[columnName]["Lesser"]] = descriptive[columnName]["Lesser"]
    # Replace outliers in the greater range
    for columnName in greater:
        dataset[columnName][dataset[columnName] > descriptive[columnName]["Greater"]] = descriptive[columnName]["Greater"]

In [46]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode",
                                "Q1:25%","Q2:50%","Q3:75%","Q4:99%","Q5:100%",
                                "IQR","1.5Rule","Lesser","Greater","Min","Max"],columns=quan)

for ColumnName in quan:
    
    descriptive[ColumnName]["Mean"]=dataset[ColumnName].mean()
    descriptive[ColumnName]["Mean"]=dataset[ColumnName].mean()
    descriptive[ColumnName]["Median"]=dataset[ColumnName].median()
    descriptive[ColumnName]["Mode"]=dataset[ColumnName].mode()[0]
    descriptive[ColumnName]["Q1:25%"]=dataset.describe()[ColumnName]["25%"] 
    descriptive[ColumnName]["Q2:50%"]=dataset.describe()[ColumnName]["50%"]
    descriptive[ColumnName]["Q3:75%"]=dataset.describe()[ColumnName]["75%"]
    descriptive[ColumnName]["Q4:99%"]=np.percentile(dataset[ColumnName],99)
    descriptive[ColumnName]["Q5:100%"]=dataset.describe()[ColumnName]["max"]
    descriptive[ColumnName]["IQR"]= descriptive[ColumnName]["Q3:75%"]-descriptive[ColumnName]["Q1:25%"]
    descriptive[ColumnName]["1.5Rule"]=1.5*descriptive[ColumnName]["IQR"]
    descriptive[ColumnName]["Lesser"]=descriptive[ColumnName]["Q1:25%"]-descriptive[ColumnName]["1.5Rule"]
    descriptive[ColumnName]["Greater"]=descriptive[ColumnName]["Q3:75%"]+descriptive[ColumnName]["1.5Rule"]
    descriptive[ColumnName]["Min"]=dataset[ColumnName].min()
    descriptive[ColumnName]["Max"]=dataset[ColumnName].max()

In [47]:
lesser=[]
greater=[]
for columnName in quan:
    if(descriptive[columnName]["Min"]<descriptive[columnName]["Lesser"]):
        lesser.append(columnName)
        if(descriptive[columnName]["Max"]>descriptive[columnName]["Greater"]):
            greater.append(columnName)

In [48]:
lesser

[]

In [49]:
greater

[]

In [51]:
dataset.to_csv('Pre_AI_Companies.csv',index=False)